www.praiser.pp.ua [Wed Feb 09 03:56:26 2022] [error] [pid 53809] mod_autoindex.c(2329): [client 188.163.113.8:45794] AH01276: Cannot serve directory /home/c/co00847/newsite/public_html/: No matching DirectoryIndex (index.php,index.htm,index.html,index.pl) found, and server-generated directory index forbidden by Options directive
www.praiser.pp.ua [Wed Feb 09 03:57:50 2022] [error] [pid 81648] src/server/mod_wsgi.c(3692): [client 188.163.113.8:55792] mod_wsgi (pid=81648): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 03:57:50 2022] [error] [pid 81648] src/server/wsgi_logger.c(630): [client 188.163.113.8:55792] mod_wsgi (pid=81648): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Wed Feb 09 03:57:50 2022] [error] [pid 81648] src/server/wsgi_logger.c(147): [client 188.163.113.8:55792] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 03:57:50 2022] [error] [pid 81648] src/server/wsgi_logger.c(147): [client 188.163.113.8:55792]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Wed Feb 09 03:57:50 2022] [error] [pid 81648] src/server/wsgi_logger.c(147): [client 188.163.113.8:55792]     from django.core.handlers import wsgi
www.praiser.pp.ua [Wed Feb 09 03:57:50 2022] [error] [pid 81648] src/server/wsgi_logger.c(147): [client 188.163.113.8:55792] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Wed Feb 09 03:57:52 2022] [error] [pid 81810] src/server/mod_wsgi.c(3692): [client 188.163.113.8:55936] mod_wsgi (pid=81810): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 03:57:52 2022] [error] [pid 81810] src/server/wsgi_logger.c(630): [client 188.163.113.8:55936] mod_wsgi (pid=81810): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Wed Feb 09 03:57:52 2022] [error] [pid 81810] src/server/wsgi_logger.c(147): [client 188.163.113.8:55936] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 03:57:52 2022] [error] [pid 81810] src/server/wsgi_logger.c(147): [client 188.163.113.8:55936]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Wed Feb 09 03:57:52 2022] [error] [pid 81810] src/server/wsgi_logger.c(147): [client 188.163.113.8:55936]     from django.core.handlers import wsgi
www.praiser.pp.ua [Wed Feb 09 03:57:52 2022] [error] [pid 81810] src/server/wsgi_logger.c(147): [client 188.163.113.8:55936] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Wed Feb 09 03:57:52 2022] [error] [pid 81869] src/server/mod_wsgi.c(3692): [client 188.163.113.8:56022] mod_wsgi (pid=81869): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 03:57:52 2022] [error] [pid 81869] src/server/wsgi_logger.c(630): [client 188.163.113.8:56022] mod_wsgi (pid=81869): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Wed Feb 09 03:57:52 2022] [error] [pid 81869] src/server/wsgi_logger.c(147): [client 188.163.113.8:56022] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 03:57:52 2022] [error] [pid 81869] src/server/wsgi_logger.c(147): [client 188.163.113.8:56022]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Wed Feb 09 03:57:52 2022] [error] [pid 81869] src/server/wsgi_logger.c(147): [client 188.163.113.8:56022]     from django.core.handlers import wsgi
www.praiser.pp.ua [Wed Feb 09 03:57:52 2022] [error] [pid 81869] src/server/wsgi_logger.c(147): [client 188.163.113.8:56022] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Wed Feb 09 03:57:53 2022] [error] [pid 81952] src/server/mod_wsgi.c(3692): [client 188.163.113.8:56078] mod_wsgi (pid=81952): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 03:57:53 2022] [error] [pid 81952] src/server/wsgi_logger.c(630): [client 188.163.113.8:56078] mod_wsgi (pid=81952): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Wed Feb 09 03:57:53 2022] [error] [pid 81952] src/server/wsgi_logger.c(147): [client 188.163.113.8:56078] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 03:57:53 2022] [error] [pid 81952] src/server/wsgi_logger.c(147): [client 188.163.113.8:56078]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Wed Feb 09 03:57:53 2022] [error] [pid 81952] src/server/wsgi_logger.c(147): [client 188.163.113.8:56078]     from django.core.handlers import wsgi
www.praiser.pp.ua [Wed Feb 09 03:57:53 2022] [error] [pid 81952] src/server/wsgi_logger.c(147): [client 188.163.113.8:56078] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Wed Feb 09 03:57:53 2022] [error] [pid 81972] src/server/mod_wsgi.c(3692): [client 188.163.113.8:56110] mod_wsgi (pid=81972): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 03:57:53 2022] [error] [pid 81972] src/server/wsgi_logger.c(630): [client 188.163.113.8:56110] mod_wsgi (pid=81972): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Wed Feb 09 03:57:53 2022] [error] [pid 81972] src/server/wsgi_logger.c(147): [client 188.163.113.8:56110] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 03:57:53 2022] [error] [pid 81972] src/server/wsgi_logger.c(147): [client 188.163.113.8:56110]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Wed Feb 09 03:57:53 2022] [error] [pid 81972] src/server/wsgi_logger.c(147): [client 188.163.113.8:56110]     from django.core.handlers import wsgi
www.praiser.pp.ua [Wed Feb 09 03:57:53 2022] [error] [pid 81972] src/server/wsgi_logger.c(147): [client 188.163.113.8:56110] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Wed Feb 09 03:57:53 2022] [error] [pid 82020] src/server/mod_wsgi.c(3692): [client 188.163.113.8:56158] mod_wsgi (pid=82020): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 03:57:53 2022] [error] [pid 82020] src/server/wsgi_logger.c(630): [client 188.163.113.8:56158] mod_wsgi (pid=82020): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Wed Feb 09 03:57:53 2022] [error] [pid 82020] src/server/wsgi_logger.c(147): [client 188.163.113.8:56158] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 03:57:53 2022] [error] [pid 82020] src/server/wsgi_logger.c(147): [client 188.163.113.8:56158]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Wed Feb 09 03:57:53 2022] [error] [pid 82020] src/server/wsgi_logger.c(147): [client 188.163.113.8:56158]     from django.core.handlers import wsgi
www.praiser.pp.ua [Wed Feb 09 03:57:53 2022] [error] [pid 82020] src/server/wsgi_logger.c(147): [client 188.163.113.8:56158] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82074] src/server/mod_wsgi.c(3692): [client 188.163.113.8:56196] mod_wsgi (pid=82074): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82074] src/server/wsgi_logger.c(630): [client 188.163.113.8:56196] mod_wsgi (pid=82074): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82074] src/server/wsgi_logger.c(147): [client 188.163.113.8:56196] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82074] src/server/wsgi_logger.c(147): [client 188.163.113.8:56196]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82074] src/server/wsgi_logger.c(147): [client 188.163.113.8:56196]     from django.core.handlers import wsgi
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82074] src/server/wsgi_logger.c(147): [client 188.163.113.8:56196] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82120] src/server/mod_wsgi.c(3692): [client 188.163.113.8:56224] mod_wsgi (pid=82120): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82120] src/server/wsgi_logger.c(630): [client 188.163.113.8:56224] mod_wsgi (pid=82120): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82120] src/server/wsgi_logger.c(147): [client 188.163.113.8:56224] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82120] src/server/wsgi_logger.c(147): [client 188.163.113.8:56224]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82120] src/server/wsgi_logger.c(147): [client 188.163.113.8:56224]     from django.core.handlers import wsgi
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82120] src/server/wsgi_logger.c(147): [client 188.163.113.8:56224] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82148] src/server/mod_wsgi.c(3692): [client 188.163.113.8:56244] mod_wsgi (pid=82148): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82148] src/server/wsgi_logger.c(630): [client 188.163.113.8:56244] mod_wsgi (pid=82148): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82148] src/server/wsgi_logger.c(147): [client 188.163.113.8:56244] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82148] src/server/wsgi_logger.c(147): [client 188.163.113.8:56244]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82148] src/server/wsgi_logger.c(147): [client 188.163.113.8:56244]     from django.core.handlers import wsgi
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82148] src/server/wsgi_logger.c(147): [client 188.163.113.8:56244] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82192] src/server/mod_wsgi.c(3692): [client 188.163.113.8:56296] mod_wsgi (pid=82192): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82192] src/server/wsgi_logger.c(630): [client 188.163.113.8:56296] mod_wsgi (pid=82192): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82192] src/server/wsgi_logger.c(147): [client 188.163.113.8:56296] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82192] src/server/wsgi_logger.c(147): [client 188.163.113.8:56296]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82192] src/server/wsgi_logger.c(147): [client 188.163.113.8:56296]     from django.core.handlers import wsgi
www.praiser.pp.ua [Wed Feb 09 03:57:54 2022] [error] [pid 82192] src/server/wsgi_logger.c(147): [client 188.163.113.8:56296] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Wed Feb 09 03:57:55 2022] [error] [pid 82296] src/server/mod_wsgi.c(3692): [client 188.163.113.8:56338] mod_wsgi (pid=82296): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 03:57:55 2022] [error] [pid 82296] src/server/wsgi_logger.c(630): [client 188.163.113.8:56338] mod_wsgi (pid=82296): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Wed Feb 09 03:57:55 2022] [error] [pid 82296] src/server/wsgi_logger.c(147): [client 188.163.113.8:56338] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 03:57:55 2022] [error] [pid 82296] src/server/wsgi_logger.c(147): [client 188.163.113.8:56338]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Wed Feb 09 03:57:55 2022] [error] [pid 82296] src/server/wsgi_logger.c(147): [client 188.163.113.8:56338]     from django.core.handlers import wsgi
www.praiser.pp.ua [Wed Feb 09 03:57:55 2022] [error] [pid 82296] src/server/wsgi_logger.c(147): [client 188.163.113.8:56338] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Wed Feb 09 03:58:21 2022] [error] [pid 102683] src/server/mod_wsgi.c(3692): [client 188.163.113.8:59678] mod_wsgi (pid=102683): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 03:58:21 2022] [error] [pid 102683] src/server/wsgi_logger.c(630): [client 188.163.113.8:59678] mod_wsgi (pid=102683): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Wed Feb 09 03:58:21 2022] [error] [pid 102683] src/server/wsgi_logger.c(147): [client 188.163.113.8:59678] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 03:58:21 2022] [error] [pid 102683] src/server/wsgi_logger.c(147): [client 188.163.113.8:59678]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Wed Feb 09 03:58:21 2022] [error] [pid 102683] src/server/wsgi_logger.c(147): [client 188.163.113.8:59678]     from django.core.handlers import wsgi
www.praiser.pp.ua [Wed Feb 09 03:58:21 2022] [error] [pid 102683] src/server/wsgi_logger.c(147): [client 188.163.113.8:59678] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Wed Feb 09 03:58:22 2022] [error] [pid 102811] src/server/mod_wsgi.c(3692): [client 188.163.113.8:59830] mod_wsgi (pid=102811): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 03:58:22 2022] [error] [pid 102811] src/server/wsgi_logger.c(630): [client 188.163.113.8:59830] mod_wsgi (pid=102811): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Wed Feb 09 03:58:22 2022] [error] [pid 102811] src/server/wsgi_logger.c(147): [client 188.163.113.8:59830] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 03:58:22 2022] [error] [pid 102811] src/server/wsgi_logger.c(147): [client 188.163.113.8:59830]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Wed Feb 09 03:58:22 2022] [error] [pid 102811] src/server/wsgi_logger.c(147): [client 188.163.113.8:59830]     from django.core.handlers import wsgi
www.praiser.pp.ua [Wed Feb 09 03:58:22 2022] [error] [pid 102811] src/server/wsgi_logger.c(147): [client 188.163.113.8:59830] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Wed Feb 09 03:58:23 2022] [error] [pid 102867] src/server/mod_wsgi.c(3692): [client 188.163.113.8:59946] mod_wsgi (pid=102867): Target WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 03:58:23 2022] [error] [pid 102867] src/server/wsgi_logger.c(630): [client 188.163.113.8:59946] mod_wsgi (pid=102867): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py'.
www.praiser.pp.ua [Wed Feb 09 03:58:23 2022] [error] [pid 102867] src/server/wsgi_logger.c(147): [client 188.163.113.8:59946] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 03:58:23 2022] [error] [pid 102867] src/server/wsgi_logger.c(147): [client 188.163.113.8:59946]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/wsgi.py", line 2, in <module>
www.praiser.pp.ua [Wed Feb 09 03:58:23 2022] [error] [pid 102867] src/server/wsgi_logger.c(147): [client 188.163.113.8:59946]     from django.core.handlers import wsgi
www.praiser.pp.ua [Wed Feb 09 03:58:23 2022] [error] [pid 102867] src/server/wsgi_logger.c(147): [client 188.163.113.8:59946] ModuleNotFoundError: No module named 'django'
www.praiser.pp.ua [Wed Feb 09 01:02:21 2022] [error] [pid 92033] src/server/wsgi_logger.c(147): [client 188.163.113.8:37810] Not Found: /static/admin/css/fonts.css
www.praiser.pp.ua [Wed Feb 09 01:04:28 2022] [error] [pid 34254] src/server/wsgi_logger.c(147): [client 188.163.113.8:53672] Not Found: /static/admin/css/fonts.css
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/mod_wsgi.c(3692): [client 188.163.113.8:43000] mod_wsgi (pid=90079): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(630): [client 188.163.113.8:43000] mod_wsgi (pid=90079): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 132, in <module>
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000]     os.path.join(BASE_DIR, "static"),
www.praiser.pp.ua [Wed Feb 09 04:06:57 2022] [error] [pid 90079] src/server/wsgi_logger.c(147): [client 188.163.113.8:43000] NameError: name 'os' is not defined
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/mod_wsgi.c(3692): [client 188.163.113.8:48136] mod_wsgi (pid=9969): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(630): [client 188.163.113.8:48136] mod_wsgi (pid=9969): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 132, in <module>
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136]     os.path.join(BASE_DIR, "static"),
www.praiser.pp.ua [Wed Feb 09 04:07:41 2022] [error] [pid 9969] src/server/wsgi_logger.c(147): [client 188.163.113.8:48136] NameError: name 'os' is not defined
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/mod_wsgi.c(3692): [client 188.163.113.8:48432] mod_wsgi (pid=10323): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(630): [client 188.163.113.8:48432] mod_wsgi (pid=10323): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 132, in <module>
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432]     os.path.join(BASE_DIR, "static"),
www.praiser.pp.ua [Wed Feb 09 04:07:43 2022] [error] [pid 10323] src/server/wsgi_logger.c(147): [client 188.163.113.8:48432] NameError: name 'os' is not defined
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/mod_wsgi.c(3692): [client 188.163.113.8:48540] mod_wsgi (pid=10617): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(630): [client 188.163.113.8:48540] mod_wsgi (pid=10617): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 132, in <module>
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540]     os.path.join(BASE_DIR, "static"),
www.praiser.pp.ua [Wed Feb 09 04:07:44 2022] [error] [pid 10617] src/server/wsgi_logger.c(147): [client 188.163.113.8:48540] NameError: name 'os' is not defined
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/mod_wsgi.c(3692): [client 188.163.113.8:48674] mod_wsgi (pid=11034): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(630): [client 188.163.113.8:48674] mod_wsgi (pid=11034): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 132, in <module>
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674]     os.path.join(BASE_DIR, "static"),
www.praiser.pp.ua [Wed Feb 09 04:07:45 2022] [error] [pid 11034] src/server/wsgi_logger.c(147): [client 188.163.113.8:48674] NameError: name 'os' is not defined
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/mod_wsgi.c(3692): [client 188.163.113.8:60652] mod_wsgi (pid=41684): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(630): [client 188.163.113.8:60652] mod_wsgi (pid=41684): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 125, in <module>
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652]     os.path.join(BASE_DIR, "static"),
www.praiser.pp.ua [Wed Feb 09 04:08:48 2022] [error] [pid 41684] src/server/wsgi_logger.c(147): [client 188.163.113.8:60652] NameError: name 'os' is not defined
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/mod_wsgi.c(3692): [client 188.163.113.8:32840] mod_wsgi (pid=42003): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(630): [client 188.163.113.8:32840] mod_wsgi (pid=42003): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 125, in <module>
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840]     os.path.join(BASE_DIR, "static"),
www.praiser.pp.ua [Wed Feb 09 04:08:49 2022] [error] [pid 42003] src/server/wsgi_logger.c(147): [client 188.163.113.8:32840] NameError: name 'os' is not defined
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/mod_wsgi.c(3692): [client 188.163.113.8:37870] mod_wsgi (pid=55090): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(630): [client 188.163.113.8:37870] mod_wsgi (pid=55090): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 125, in <module>
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870]     os.path.join(BASE_DIR, "static"),
www.praiser.pp.ua [Wed Feb 09 04:09:08 2022] [error] [pid 55090] src/server/wsgi_logger.c(147): [client 188.163.113.8:37870] NameError: name 'os' is not defined
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/mod_wsgi.c(3692): [client 188.163.113.8:38140] mod_wsgi (pid=56367): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(630): [client 188.163.113.8:38140] mod_wsgi (pid=56367): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 125, in <module>
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140]     os.path.join(BASE_DIR, "static"),
www.praiser.pp.ua [Wed Feb 09 04:09:09 2022] [error] [pid 56367] src/server/wsgi_logger.c(147): [client 188.163.113.8:38140] NameError: name 'os' is not defined
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/mod_wsgi.c(3692): [client 188.163.113.8:38274] mod_wsgi (pid=57034): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(630): [client 188.163.113.8:38274] mod_wsgi (pid=57034): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 125, in <module>
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274]     os.path.join(BASE_DIR, "static"),
www.praiser.pp.ua [Wed Feb 09 04:09:10 2022] [error] [pid 57034] src/server/wsgi_logger.c(147): [client 188.163.113.8:38274] NameError: name 'os' is not defined
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/mod_wsgi.c(3692): [client 176.113.42.164:42514] mod_wsgi (pid=69399): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(630): [client 176.113.42.164:42514] mod_wsgi (pid=69399): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514] Traceback (most recent call last):
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]     django.setup()
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]     self._setup(name)
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]     self._wrapped = Settings(settings_module)
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]     mod = importlib.import_module(self.SETTINGS_MODULE)
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]     return _bootstrap._gcd_import(name[level:], package, level)
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 125, in <module>
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514]     os.path.join(BASE_DIR, "static"),
praiser.pp.ua [Wed Feb 09 04:09:28 2022] [error] [pid 69399] src/server/wsgi_logger.c(147): [client 176.113.42.164:42514] NameError: name 'os' is not defined
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/mod_wsgi.c(3692): [client 188.163.113.8:51298] mod_wsgi (pid=97124): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(630): [client 188.163.113.8:51298] mod_wsgi (pid=97124): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]   File "<frozen importlib._bootstrap_external>", line 674, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]   File "<frozen importlib._bootstrap_external>", line 781, in get_code
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]   File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 123
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]     STATIC_ROOT = '/home/c/co00847/newsite/public_html/static''
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298]                                                               ^
www.praiser.pp.ua [Wed Feb 09 04:10:23 2022] [error] [pid 97124] src/server/wsgi_logger.c(147): [client 188.163.113.8:51298] SyntaxError: EOL while scanning string literal
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/mod_wsgi.c(3692): [client 188.163.113.8:51448] mod_wsgi (pid=97261): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(630): [client 188.163.113.8:51448] mod_wsgi (pid=97261): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]   File "<frozen importlib._bootstrap_external>", line 674, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]   File "<frozen importlib._bootstrap_external>", line 781, in get_code
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]   File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 123
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]     STATIC_ROOT = '/home/c/co00847/newsite/public_html/static''
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448]                                                               ^
www.praiser.pp.ua [Wed Feb 09 04:10:25 2022] [error] [pid 97261] src/server/wsgi_logger.c(147): [client 188.163.113.8:51448] SyntaxError: EOL while scanning string literal
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/mod_wsgi.c(3692): [client 188.163.113.8:51546] mod_wsgi (pid=97412): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(630): [client 188.163.113.8:51546] mod_wsgi (pid=97412): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]   File "<frozen importlib._bootstrap_external>", line 674, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]   File "<frozen importlib._bootstrap_external>", line 781, in get_code
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]   File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 123
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]     STATIC_ROOT = '/home/c/co00847/newsite/public_html/static''
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546]                                                               ^
www.praiser.pp.ua [Wed Feb 09 04:10:26 2022] [error] [pid 97412] src/server/wsgi_logger.c(147): [client 188.163.113.8:51546] SyntaxError: EOL while scanning string literal
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/mod_wsgi.c(3692): [client 188.163.113.8:54566] mod_wsgi (pid=101381): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(630): [client 188.163.113.8:54566] mod_wsgi (pid=101381): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]   File "<frozen importlib._bootstrap_external>", line 674, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]   File "<frozen importlib._bootstrap_external>", line 781, in get_code
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]   File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 121
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]     STATIC_ROOT = '/home/c/co00847/newsite/public_html/static''
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566]                                                               ^
www.praiser.pp.ua [Wed Feb 09 04:10:53 2022] [error] [pid 101381] src/server/wsgi_logger.c(147): [client 188.163.113.8:54566] SyntaxError: EOL while scanning string literal
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/mod_wsgi.c(3692): [client 188.163.113.8:54712] mod_wsgi (pid=101494): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(630): [client 188.163.113.8:54712] mod_wsgi (pid=101494): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]   File "<frozen importlib._bootstrap_external>", line 674, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]   File "<frozen importlib._bootstrap_external>", line 781, in get_code
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]   File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 121
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]     STATIC_ROOT = '/home/c/co00847/newsite/public_html/static''
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712]                                                               ^
www.praiser.pp.ua [Wed Feb 09 04:10:54 2022] [error] [pid 101494] src/server/wsgi_logger.c(147): [client 188.163.113.8:54712] SyntaxError: EOL while scanning string literal
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/mod_wsgi.c(3692): [client 188.163.113.8:54848] mod_wsgi (pid=101629): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(630): [client 188.163.113.8:54848] mod_wsgi (pid=101629): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]   File "<frozen importlib._bootstrap_external>", line 674, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]   File "<frozen importlib._bootstrap_external>", line 781, in get_code
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]   File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 121
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]     STATIC_ROOT = '/home/c/co00847/newsite/public_html/static''
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848]                                                               ^
www.praiser.pp.ua [Wed Feb 09 04:10:55 2022] [error] [pid 101629] src/server/wsgi_logger.c(147): [client 188.163.113.8:54848] SyntaxError: EOL while scanning string literal
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/mod_wsgi.c(3692): [client 188.163.113.8:54928] mod_wsgi (pid=101714): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(630): [client 188.163.113.8:54928] mod_wsgi (pid=101714): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]   File "<frozen importlib._bootstrap_external>", line 674, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]   File "<frozen importlib._bootstrap_external>", line 781, in get_code
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]   File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 121
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]     STATIC_ROOT = '/home/c/co00847/newsite/public_html/static''
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928]                                                               ^
www.praiser.pp.ua [Wed Feb 09 04:10:56 2022] [error] [pid 101714] src/server/wsgi_logger.c(147): [client 188.163.113.8:54928] SyntaxError: EOL while scanning string literal
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/mod_wsgi.c(3692): [client 188.163.113.8:56804] mod_wsgi (pid=9529): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(630): [client 188.163.113.8:56804] mod_wsgi (pid=9529): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]   File "<frozen importlib._bootstrap_external>", line 674, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]   File "<frozen importlib._bootstrap_external>", line 781, in get_code
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]   File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 121
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]     STATIC_ROOT = '/home/c/co00847/newsite/public_html/static''
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804]                                                               ^
www.praiser.pp.ua [Wed Feb 09 04:11:10 2022] [error] [pid 9529] src/server/wsgi_logger.c(147): [client 188.163.113.8:56804] SyntaxError: EOL while scanning string literal
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/mod_wsgi.c(3692): [client 188.163.113.8:34762] mod_wsgi (pid=25503): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(630): [client 188.163.113.8:34762] mod_wsgi (pid=25503): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]   File "<frozen importlib._bootstrap_external>", line 674, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]   File "<frozen importlib._bootstrap_external>", line 781, in get_code
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]   File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 121
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]     STATIC_ROOT = '/home/c/co00847/newsite/public_html/static''
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762]                                                               ^
www.praiser.pp.ua [Wed Feb 09 04:12:03 2022] [error] [pid 25503] src/server/wsgi_logger.c(147): [client 188.163.113.8:34762] SyntaxError: EOL while scanning string literal
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/mod_wsgi.c(3692): [client 188.163.113.8:35486] mod_wsgi (pid=33050): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(630): [client 188.163.113.8:35486] mod_wsgi (pid=33050): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]   File "<frozen importlib._bootstrap_external>", line 674, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]   File "<frozen importlib._bootstrap_external>", line 781, in get_code
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]   File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 121
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]     STATIC_ROOT = '/home/c/co00847/newsite/public_html/static''
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486]                                                               ^
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33050] src/server/wsgi_logger.c(147): [client 188.163.113.8:35486] SyntaxError: EOL while scanning string literal
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/mod_wsgi.c(3692): [client 188.163.113.8:35628] mod_wsgi (pid=33818): Target WSGI script '/home/c/co00847/newsite/public_html/index.wsgi' cannot be loaded as Python module.
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(630): [client 188.163.113.8:35628] mod_wsgi (pid=33818): Exception occurred processing WSGI script '/home/c/co00847/newsite/public_html/index.wsgi'.
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628] Traceback (most recent call last):
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]   File "/home/c/co00847/newsite/public_html/index.wsgi", line 8, in <module>
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]     django.setup()
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]     self._setup(name)
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]     self._wrapped = Settings(settings_module)
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]   File "/home/c/co00847/newsite/myenv/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]     mod = importlib.import_module(self.SETTINGS_MODULE)
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]     return _bootstrap._gcd_import(name[level:], package, level)
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]   File "<frozen importlib._bootstrap_external>", line 674, in exec_module
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]   File "<frozen importlib._bootstrap_external>", line 781, in get_code
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]   File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]   File "/home/c/co00847/newsite/public_html/kankuvisit/kankuvisit/settings.py", line 121
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]     STATIC_ROOT = '/home/c/co00847/newsite/public_html/static''
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628]                                                               ^
www.praiser.pp.ua [Wed Feb 09 04:12:09 2022] [error] [pid 33818] src/server/wsgi_logger.c(147): [client 188.163.113.8:35628] SyntaxError: EOL while scanning string literal
